# Generated by Django 4.2.6 on 2023-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('department', models.CharField(max_length=256, verbose_name='Цех')),
                ('employee', models.CharField(max_length=128, verbose_name='Сотрудник')),
                ('brigade', models.PositiveSmallIntegerField(verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
            },
        ),
    ]
